package-lock.json, package.json, src/Logger.js, src/index.js, test/logger.test.js
=> Add common logging #2

src/Logger.js, test/logger.test.js
=> generate json logs when logfile ends with .json #4

package-lock.json, package.json, src/Origin.js, src/Strain.js, test/config.test.js, test/origin.test.js, test/specs/configs/empty.json, test/specs/configs/full.json, test/specs/configs/full.yaml, test/specs/configs/urls.json, test/specs/configs/urls.yaml
This is a (partial) fix for #9 and needed for adobe/helix-cli#348 to implement adobe/helix-cli#347
=> WIP: Support Origins, Sticky Strains

src/GitUrl.js, test/giturl.test.js
=> [GitUrl] scp-style url does not extract branch name properly #16

src/GitUrl.js, test/giturl.test.js
=> Improve error messages for invalid git urls

src/Strain.js, test/config.test.js, test/specs/configs/minimal-clone-code-package.yaml
=> modifying extended strain removes merge #39

package-lock.json, package.json, src/Strain.js
=> toYAML() shows error: YAML_MAP is not a constructor #44

src/Static.js, src/Strain.js, test/strains.test.js
=> Static: emit events to notify Strains about changes #49

.circleci/config.yml, CONTRIBUTING.md, package-lock.json, package.json
=> build(package): Adopt semantic-release

CONFIGURATION.md
From a Slack thread to an issue (#11) from an issue to a PR.
=> Discussion: New Configuration Design Spec

test/performance.test.js
=> test(performance): Add unit tests for thresholds getter

.circleci/config.yml
PR for https://github.com/adobe/helix-shared/issues/78
=> Integrate the smoke tests

src/sequence.js, src/string.js, test/sequence.test.js, test/string.test.js
=> Helpers for implementing improved frontmatter in helix-pipe

CONFIGURATION.md
=> updating strain examples to use new strain sequence format

src/GitUrl.js, src/Static.js, src/Strain.js, test/giturl.test.js, test/specs/configs/perf.json, test/specs/configs/urls.json, test/strains.test.js
=> fix(config): Ensure default ref is added to string giturls

src/Static.js, src/Strain.js
=> fix(yaml): Avoid deprecation warnings from yaml

src/dom.js, test/dom.test.js
=> fix(dom): normalize className attributes before comparison

.eslintrc.js, package.json, src/dom.js, src/functional.js, src/index.js, src/op.js, src/sequence.js, src/string.js, src/types.js, test/dom.test.js, test/functional.test.js, test/op.test.js, test/sequence.test.js, test/string.test.js, test/types.test.js, test/util.js
Specifically this introduces the traits Equals, Shallowclone and Deepclone.
=> Utilities for working with advanced types

package-lock.json, package.json
=> Greenkeeper/eslint plugin import 2.17.3

package-lock.json, package.json
=> Greenkeeper/lint staged 9.0.1

package.json, src/HelixConfig.js, src/Logger.js, src/index.js, src/log.js, test/config.test.js, test/log.test.js, test/logger.test.js, test/specs/configs/full-canonical.yaml
=> fix(logger): export Logger again to keep module backward compatible

package-lock.json, package.json
=> Greenkeeper/@adobe/eslint config helix 1.0.1

docs/proxystrain.schema.json, docs/proxystrain.schema.md, docs/runtimestrain.schema.json, docs/runtimestrain.schema.md, package-lock.json, src/Strain.js, src/schemas/proxystrain.schema.json, src/schemas/runtimestrain.schema.json, test/strains.test.js
=> fix: Deprecate url in the strain schema

package-lock.json, src/Condition.js, src/Strain.js, test/condition.test.js, test/specs/conditions/null.yaml, test/specs/conditions/string.yaml, test/specs/configs/clone-tests.yaml, test/strains.test.js
- implements #146 
- rework Condition to use methods for both objects and strings
- change strain test to use Condition object
=> feat: Conditions should be serialisable to JSON

package-lock.json, package.json, test/condition.test.js
=> Greenkeeper/nock 11.3.3

package-lock.json, package.json
=> chore(dev): re-add commitizen

src/Strain.js
=> fix: Deprecation warnings should be shown just once per run

package-lock.json, package.json
=> Greenkeeper/ferrum 1.4.1

CONFIGURATION.md
As far as I could tell, all other examples in the `README` conform to the current specification.
Resolves #101
=> docs: fix example

src/Strain.js
=> feat(strain): add url deprecation example

test/async.test.js, test/dom.test.js, test/log.test.js, test/string.test.js
- some of the tests were failing on slower systems due to timeouts -> timeouts raised
- many of the tests were not part of a `describe` group -> cleaned up
=> Increase Test Robustness

.circleci/config.yml
=> chore(ci): update to node 10

src/Condition.js, test/condition.test.js, test/specs/conditions/or2.yaml, test/specs/conditions/or3.yaml, test/specs/conditions/or4.yaml, test/specs/conditions/url_path.yaml, test/specs/conditions/url_startswith.yaml
=> fix(condition): toVCLPath should not return

src/IndexConfig.js, test/indexconfigs.test.js
=> feat(query): add method for resolving query URL

src/IndexConfig.js, src/MarkupConfig.js, src/MountConfig.js, src/SchemaDerivedConfig.js
=> fix(schema): ensure the schemas are 'required()'

src/Origin.js, test/specs/configs/comments.json, test/specs/configs/full-canonical.yaml, test/specs/configs/full.json, test/specs/configs/urls.json, test/strains.test.js
=> fix(proxy): use non-deprecated backend for proxy strains

renovate.json
=> chore(renovate): add encrypted npm token for private repos

src/DynamicRedirect.js
I forgot to make sure the body is always read
=> fix(redirects): fix hanging HTTP requests

src/index.js
fixes https://github.com/adobe/helix-redirect/pull/21#discussion_r446144608
=> feat(redirects): export redirects in index

renovate.json
=> build(renovate): automerge all minor updates at any time

src/DynamicRedirect.js, test/redirectconfigs.test.js
allow (but ignore) hostnames, match spaces
fixes #353 #352
=> fix(redirects): relax redirect from matching

src/schemas/index.schema.json, src/schemas/query.schema.json, test/indexconfigs.test.js, test/specs/queryconfigs/qbl-query.json, test/specs/queryconfigs/qbl-query.yaml
- allow `target` property
- allow QBL expressions
fixes #323
=> Update Query schema

test/redirectconfigs.test.js, test/specs/redirectsconfig/feeds.json, test/specs/redirectsconfig/feeds.yaml
Tests for #360, verifying that the error must be elsewhere.
=> Dude where is my feed

src/MountConfig.js, test/mountpoints.test.js, test/specs/mountconfigs/complex.json, test/specs/mountconfigs/complex.yaml
=> fix(fstab): make gdrive mountpoints more robust

src/schemas/conditions.schema.json, src/schemas/config.schema.json
other names considered and dismissed: delegate, preconditions
see https://github.com/adobe/helix-publish/issues/349
=> feat(schema): add preflight conditions

renovate.json
=> chore: temporarily disable automerge

src/BaseConfig.js
=> fix: use git url first if specified

src/Strain.js, test/specs/configs/full-canonical.yaml, test/specs/configs/full-map.yaml, test/specs/configs/full.json, test/specs/configs/full.yaml
add the `version-lock` property also to the strain class.
=> fix(cfg): add version lock property to json and strain

src/MountConfig.js, test/mountpoints.test.js, test/specs/mountconfigs/complex.json, test/specs/mountconfigs/complex.yaml
=> feat(fstab): add support for github mount points

src/dom.js, test/dom.test.js
=> fix(test): tests that reveals the issue

.circleci/config.yml, package-lock.json, package.json, src/DynamicRedirect.js, src/fetchconfig/fetch.js, test/mountpoints.test.js, test/redirectconfigs.test.js
=> fix(deps): update to helix-fetch v2

.vscode/launch.json, package-lock.json, package.json, src/fetchconfig/fetch.js, test/backendmapping.test.js
=> test: fix hanging tests

package-lock.json, package.json, src/DynamicRedirect.js, test/condition.test.js, test/redirectconfigs.test.js, test/specs/redirectsconfig/dynamic.yaml, test/specs/redirectsconfig/redirects.json
=> feat(redirect): allow fetching json directly

src/schemas/config.schema.json
=> feat(config): allow universal runtime URLs as preflight URLs

src/DynamicRedirect.js, test/redirectconfigs.test.js
=> fix(redirect): fix dynamic redirects via json

package.json, src/index.d.ts, src/index.js, src/wrap.d.ts, src/wrap.js, test/wrap.test.js
Adds a new function wrap (from https://github.com/adobe/openwhisk-action-utils/blob/main/src/wrap.js).
this helps to disassociate universal functions from openwhisk.
=> feat(wrap): add wrap function

src/DynamicRedirect.js, src/Redirect.js, src/RedirectConfig.js, test/redirectconfigs.test.js
- refactor(redirect): extract fetch method
- feat(redirect): add RedirectConfig.all method that lists all redirects
=> list all redirects

renovate.json
=> chore: ignore more versions [skip ci]

package-lock.json, src/config-wrapper.js
=> fix: context.invocation might be missing

packages/helix-shared-config/package-lock.json, packages/helix-shared-config/src/schemas/index.schema.json, packages/helix-shared-config/test/indexconfigs.test.js, packages/helix-shared-config/test/specs/queryconfigs/query.json, packages/helix-shared-config/test/specs/queryconfigs/query.yaml
In light of https://github.com/adobe/helix-excel-indexer/issues/274 `target` should be allowed to be relative
=> feat: target URI should be allowed relative

.circleci/config.yml, packages/helix-shared-indexer/.jsdoc.json, packages/helix-shared-indexer/.mocha-multi.json, packages/helix-shared-indexer/.npmignore, packages/helix-shared-indexer/.nycrc.json, packages/helix-shared-indexer/CHANGELOG.md, packages/helix-shared-indexer/LICENSE.txt, packages/helix-shared-indexer/README.md, packages/helix-shared-indexer/package-lock.json, packages/helix-shared-indexer/package.json, packages/helix-shared-indexer/src/index-resource.d.ts, packages/helix-shared-indexer/src/index-resource.js, packages/helix-shared-indexer/test/index-resource.test.js
shared functionality to index html based on the index config
=> feat: add shared index

.circleci/config.yml, packages/helix-shared-bounce/.jsdoc.json, packages/helix-shared-bounce/.mocha-multi.json, packages/helix-shared-bounce/.npmignore, packages/helix-shared-bounce/.nycrc.json, packages/helix-shared-bounce/CHANGELOG.md, packages/helix-shared-bounce/LICENSE.txt, packages/helix-shared-bounce/README.md, packages/helix-shared-bounce/package-lock.json, packages/helix-shared-bounce/package.json, packages/helix-shared-bounce/src/bounce.d.ts, packages/helix-shared-bounce/src/bounce.js, packages/helix-shared-bounce/test/bounce.test.js
This is meant as a generic solution of adobe/helix-slack-bot#221
=> feat(bounce): add new middleware to bounce slow running functions and get a fast response

packages/helix-shared-bounce/package-lock.json, packages/helix-shared-bounce/package.json, packages/helix-shared-bounce/src/bounce.js, packages/helix-shared-bounce/test/bounce.test.js
Bounce aborted will return a 504 status code, bounce failed will return a 502 status code, promise rejection will be handled in any case
see https://cq-dev.slack.com/archives/CGG9B79BK/p1641723669007900?thread_ts=1641722889.000900&cid=CGG9B79BK
=> fix(bounce): add better error handling for promise rejections in bounce

packages/helix-shared-body-data/src/body-data-wrapper.js, packages/helix-shared-body-data/test/body-data-wrapper.test.js, packages/helix-shared-ims/package.json
=> fix: ignore non body bearing methods for json and form-data

.circleci/config.yml, package-lock.json, package.json
- ci(circleci): increase parallelism
- ci(circleci): increase parallelism
- ci(circleci): run lint in parallel, too
=> Run Builds in parallel

packages/helix-shared-utils/package-lock.json, packages/helix-shared-utils/src/utils.js
=> fix: fix webcrypto calls for non-node env

packages/helix-shared-config/src/IndexConfig.js, packages/helix-shared-config/src/SchemaDerivedConfig.js, packages/helix-shared-config/test/specs/queryconfigs/broken.json, packages/helix-shared-config/test/specs/queryconfigs/qbl-query.json, packages/helix-shared-config/test/specs/queryconfigs/query.json, packages/helix-shared-config/test/specs/sitemapconfigs/multilang.json, packages/helix-shared-config/test/specs/sitemapconfigs/simple.json
=> fix: proxy clone to not change original configuration

package-lock.json, packages/helix-shared-indexer/package.json, packages/helix-shared-indexer/src/index-resource.js, packages/helix-shared-indexer/test/index-resource.test.js
in #691 we removed innerHTML, adding it back
=> fix: add back innerHTML

.eslintrc.js, packages/helix-shared-config/src/ModifiersConfig.d.ts, packages/helix-shared-config/src/ModifiersConfig.js, packages/helix-shared-config/src/index.d.ts, packages/helix-shared-config/src/index.js, packages/helix-shared-config/test/fixtures/content/metadata-kv.json, packages/helix-shared-config/test/fixtures/content/metadata.json, packages/helix-shared-config/test/modifiers-config.test.js
add `ModifiersConfig` - currently needed by html-pipeline, but also for https://github.com/adobe/helix-admin/issues/726
=> feat: add modifiers config

packages/helix-shared-utils/package.json, packages/helix-shared-utils/src/crypto.node.js, packages/helix-shared-utils/src/crypto.worker.js, packages/helix-shared-utils/src/utils.js
=> feat: improve cross platform compatibilty with conditional crypto import

package-lock.json, packages/helix-shared-body-data/package.json, packages/helix-shared-body-data/src/body-data-wrapper.js, packages/helix-shared-body-data/test/body-data-wrapper.test.js, packages/helix-shared-bounce/README.md, packages/helix-shared-bounce/package.json, packages/helix-shared-bounce/src/bounce.d.ts, packages/helix-shared-bounce/src/bounce.js, packages/helix-shared-bounce/test/bounce.test.js, packages/helix-shared-config/package.json, packages/helix-shared-config/src/SitemapHandler.js, packages/helix-shared-config/src/config-wrapper.js, packages/helix-shared-config/src/fetchconfig/fetch.js, packages/helix-shared-config/test/config-wrapper.test.js, packages/helix-shared-config/test/fixtures/Mount-Point-Config-Loading-from-GitHub_685459252/Missing-File-from-GitHub-treated-as-empty_3962725678/recording.har, packages/helix-shared-config/test/fixtures/Mount-Point-Config-Loading-from-GitHub_685459252/Retrieves-Document-from-GitHub_3329037324/recording.har, packages/helix-shared-config/test/fixtures/Optional-Config-Loading-Wrapper_2750564974/Config-is-loaded-when-request-is-a-Form-body_939328368/recording.har, packages/helix-shared-config/test/fixtures/Optional-Config-Loading-Wrapper_2750564974/Config-is-loaded-when-request-is-a-JSON-body_2882656888/recording.har, packages/helix-shared-config/test/fixtures/Required-Config-Loading-Wrapper_1405900573/Unloadable-required-config-causes-status-502_933809436/recording.har, packages/helix-shared-config/test/setup-env.js, packages/helix-shared-ims/package.json, packages/helix-shared-ims/src/ims.js, packages/helix-shared-ims/test/ims.test.js, packages/helix-shared-ims/test/setup-env.js, packages/helix-shared-indexer/package.json, packages/helix-shared-indexer/src/index.d.ts, packages/helix-shared-indexer/test/index-resource.test.js
=> fix: @adobe/helix-fetch -> @adobe/helix

packages/helix-shared-indexer/src/index-resource.js, packages/helix-shared-indexer/test/index-resource.test.js
=> fix: catch unsupported selectors

package-lock.json, packages/helix-shared-tokencache/.jsdoc.json, packages/helix-shared-tokencache/.mocha-multi.json, packages/helix-shared-tokencache/.npmignore, packages/helix-shared-tokencache/.nycrc.json, packages/helix-shared-tokencache/LICENSE.txt, packages/helix-shared-tokencache/README.md, packages/helix-shared-tokencache/package.json, packages/helix-shared-tokencache/src/FSCacheManager.d.ts, packages/helix-shared-tokencache/src/FSCacheManager.js, packages/helix-shared-tokencache/src/FSCachePlugin.d.ts, packages/helix-shared-tokencache/src/FSCachePlugin.js, packages/helix-shared-tokencache/src/MemCachePlugin.d.ts, packages/helix-shared-tokencache/src/MemCachePlugin.js, packages/helix-shared-tokencache/src/S3CacheManager.d.ts, packages/helix-shared-tokencache/src/S3CacheManager.js, packages/helix-shared-tokencache/src/S3CachePlugin.d.ts, packages/helix-shared-tokencache/src/S3CachePlugin.js, packages/helix-shared-tokencache/src/encrypt.js, packages/helix-shared-tokencache/src/index.d.ts, packages/helix-shared-tokencache/src/index.js, packages/helix-shared-tokencache/test/MockTokenCacheContext.js, packages/helix-shared-tokencache/test/encrypt.test.js, packages/helix-shared-tokencache/test/fs-cache-manager.test.js, packages/helix-shared-tokencache/test/fs-cache-plugin.test.js, packages/helix-shared-tokencache/test/mem-cache-plugin.test.js, packages/helix-shared-tokencache/test/s3-cache-manager.test.js, packages/helix-shared-tokencache/test/s3-cache-plugin.test.js, packages/helix-shared-tokencache/test/setup-env.js, packages/helix-shared-tokencache/test/utils.js
move from https://github.com/adobe/helix-onedrive-support/tree/main/src/cache
=> fix: move tokencache plugin from onedrive support

package-lock.json, packages/helix-shared-config/package.json
for helix-admin security problem: https://github.com/adobe/helix-admin/security/dependabot/49
=> fix(deps): remove yaml@2.1.1 by updating helix-shared-git dependency

packages/helix-shared-tokencache/src/getCachePlugin.js, packages/helix-shared-tokencache/test/getCachePlugin.test.js
=> feat: add support for owner global connected users

packages/helix-shared-config/src/SitemapConfig.js, packages/helix-shared-config/test/sitemapconfigs.test.js
related to https://github.com/adobe/helix-admin/issues/1199
=> feat: set origin of sitemap

packages/helix-shared-indexer/src/index-resource.js, packages/helix-shared-indexer/test/index-resource.test.js
=> fix: issues 837/838

package-lock.json, package.json, renovate.json5
This reverts commit da19f8fd596d4477069bdda52eb247926774d72c.
=> fix: Revert "chore: use semantic-release-monorepo-esm (#867)"

package-lock.json, packages/helix-shared-secrets/README.md, packages/helix-shared-secrets/src/secrets-wrapper.js, packages/helix-shared-secrets/test/secrets-wrapper.test.js
Follow-up to PR #879 due early merge.
=> fix: default path for name-function and usage example
