adobe/helix-shared

docs/README.md, docs/giturl.schema.json, docs/giturl.schema.md, docs/origin.schema.json, docs/proxystrain.schema.json, docs/proxystrain.schema.md, docs/runtimestrain.schema.json, docs/runtimestrain.schema.md, docs/staticgiturl.schema.json, docs/staticgiturl.schema.md, src/ConfigValidator.js, src/HelixConfig.js, src/Origin.js, src/Strain.js, src/schemas/giturl.schema.json, src/schemas/origin.schema.json, src/schemas/proxystrain.schema.json, src/schemas/runtimestrain.schema.json, src/schemas/staticgiturl.schema.json, test/config.test.js, test/specs/configs/full.json, test/specs/configs/full.yaml, test/specs/configs/perf.json, test/specs/configs/urls.json
Adds add `fromJSON` method to initialize a Helix Config from another HelixConfig's `.toJSON` output.
I had to adjust some of the schemas and some of the output to make it roundtripable.
=> creating configs from an existing toJSON() object

.eslintrc.js, package.json, src/dom.js, src/index.js, src/sequence.js, test/dom.test.js, test/sequence.test.js, test/strains.test.js
These utilities are used in my https://github.com/adobe/helix-pipeline/pull/163 PR.
Unfortunately comparing dom trees while discarding insignificant whitespace changes is rather more complex than I anticipated and I could not find a library that decently implements whitespace collapsing
for html trees, so I had to come up with my own solution based on the html5 spec.
=> Add utilities for comparing dom trees

docs/README.md, docs/proxystrain.schema.json, docs/proxystrain.schema.md, docs/redirectrule.schema.json, docs/redirectrule.schema.md, docs/runtimestrain.schema.json, docs/runtimestrain.schema.md, src/ConfigValidator.js, src/Redirect.js, src/Strain.js, src/schemas/proxystrain.schema.json, src/schemas/redirectrule.schema.json, src/schemas/runtimestrain.schema.json, test/redirects.test.js, test/specs/configs/full.json, test/specs/configs/full.yaml, test/strains.test.js
Enables the definition of a list of `redirects` for a strain. Each item in the list is a a pair of
`from` (regex) and `to` (replacement pattern) tuples
Fixes #59
=> feat(strains): Add support for Redirect rules

package-lock.json, package.json, test/config.test.js, test/specs/configs/comments.json, test/specs/configs/various_comments.yaml
=> fix(config): Use latest yaml parser to fix bug with comments

docs/performance.schema.json, docs/performance.schema.md, src/schemas/performance.schema.json, test/specs/configs/perf.yaml, test/validator.test.js
The performance metrics that determine what the minimum performance goals for a strain are have been missing from the schema, making it impossible to actually compare performance against
self-determined thresholds. This change adds the missing schemas and updates the documentation
=> fix(schema): Add schema for missing performance metrics

docs/conditions.schema.json, docs/conditions.schema.md, src/schemas/conditions.schema.json, test/specs/configs/valid-conditions.yaml
`and` and `or` must be arrays. `conditions` and `not` must have exactly one property
Fixes #95 and fixes #96
=> fix(conditions): restrict conditions schema

src/HelixConfig.js, test/config.test.js
required for https://github.com/adobe/helix-cli/issues/821
=> allow merging of configs

src/index.js, src/utils.js, test/surrogate.test.js
=> feat(utils): Add function to calculate surrogate key

src/GitUrl.js, test/giturl.test.js
=> fix(giturl): use githubusercontent for raw url

renovate.json
Enable automerging for CircleCI orb updates of type minor and patch.
=> chore(deps): automerge minor & patch orb updates

src/schemas/markupmapping.description.md, src/schemas/markupmapping.schema.json
- Add separate examples for each property for both markdown and HTML types.
- Add combined example as well
Quick review: https://github.com/adobe/helix-shared/blob/188f70d0c92696578615157229575359b1ec317f/src/schemas/markupmapping.description.md
=> docs(html pipe): documenting markup config examples

src/Condition.js, test/specs/conditions/url_slash.yaml
=> fix(condition): prefix match fails if already contains trailing slash

package-lock.json, src/IndexConfig.js, src/SchemaDerivedConfig.js, test/mountpoints.test.js
This fixes an issue introduced in #296 that prevented running the `.match()` function on empty mount configs
=> Fix for missing fiterability in empty mount configs

src/BaseConfig.js, src/fetchconfig/cache.js, src/fetchconfig/fetch.js, test/mountpoints.test.js
Adds a new method `BaseConfig.withRepoURL()` that allows to set the git coordinates using a git url. this has the advantage, that it also contains the repository root.
=> feat(config): add 'withRepoURL(GitUrl)' to base config

renovate.json
simplified the renovate config:
- all external packages are updated every week, automege only disabled to major updates.
- all internal packages are updated any time, automege only disabled to major updates.
=> chore(renovate): simplified config

src/MountConfig.js, src/MountPointHandler.js, test/mountpoints.test.js, test/specs/mountconfigs/complex.json, test/specs/mountconfigs/complex.yaml
fixes #342
- also adds support for `onedrive:` uris see https://github.com/adobe/helix-onedrive-support/issues/68
- this will fix https://github.com/adobe/helix-word2md/issues/70 once added to content proxy
=> feat(mount): support mounting of documents

renovate.json
limits the webpack version to `4.x`.
=> chore(renovate): limit webpack version

renovate.json
using a branch prefix `renovate_` should avoid problems with smoke tests in helix-pages (and helix-index-files)
=> chore: set renovate branch prefix

src/Strain.js, test/config.test.js, test/specs/configs/minimal-lock-package.yaml, test/specs/configs/minimal-lock.yaml
=> fix(yaml): modified strain doesn't preserve version-lock on save

src/utils.js, test/backendmapping.test.js
Fix adobe/helix-content-proxy#239
Impact is limited since the method `logLevelForStatusCode ` is used only in the content-proxy and data-embed where in both cases we only want an info log entry for 4xx.
=> feat(log): info on 4xx

src/DynamicRedirect.js, test/redirectconfigs.test.js
Note: reading the PR description might be harmful to your mental health and may lead to questioning your sanity.
the blog is using a url with ä (cyrillic) instead of ӓ (latin) and redirect definitions do not take hold because when entering the cyrillic character in excel, it will autocorrect to the latin character, which does not match, and there is no adequate normalization available either. So the (narrow) workaround is to put the URL encoded variants (both, in both possible capitalizations) into the spreadsheet and extend the matching to URL encode both variants of ä and ӓ when encountered.
Also, at least on macOS, entering ӓ (latin) into a text field that already contains an ä (cyrillic) will replace the latin with the cyrillic, so make sure to copy and paste.
=> fix(redirects): handle special case of äӓ confusion

src/schemas/runtimestrain.schema.json
prior to the change, the package parameter was simply a string, now it is either 
- (1) a string without slashes – old format, 
- (2) a string with exactly one slash – current format, 
- (3) a URI – new format
=> refactor(schema): clarify the format of the package parameter

src/DynamicRedirect.js
As a precautionary measure HTTP/2 had been disabled in order to avoid issues related to the runtime migration to Azure. We've since re-implemented the http client (fetch) and now it's time to re-enable HTTP/2.
> Note that flag to disable HTTP/2 (an env variable) had leaked to all dependants of `helix-shared`, effectively disabling HTTP/2 there too.
=> fix: re-enable HTTP/2

src/schemas/index.schema.json
Noticed while adding a new index in a project and forgetting one of those. These should all be required.
Note, that `target` - when omitted - defaults to an Algolia index. Might be worth changing this behaviour, e.g. make `target` required as well.
=> fix: make some properties required

src/BaseConfig.js, src/DynamicRedirect.js, src/RedirectConfig.js, src/RedirectRuleHandler.js, test/mountpoints.test.js, test/redirectconfigs.test.js
Fixes #480 by:
- using universal runtime instead of adobe i/o runtime
- passing the github token along
Drive-by-fixes:
- now uses data-embed@v2 (so we get the last six months of fixes and features)
Non-fixes (because they are non-issues)
- if the specified URL ends with `.json`, it is still being fetched directly, and with that using helix-content-proxy and the associated caches in most cases
Potential new issues
- the GitHub token is passed to all URLs ending with `.json`, and this includes potentially external servers that could grab the token from the request. We do not have a way of validating if a given external URL corresponds to a helix site on a private repo and thus needs the token or if sending the token is unneccessary or potentially harmful.
=> use universal runtime for redirects

src/index.d.ts, src/index.js, src/process-queue.d.ts, src/process-queue.js, test/process-queue.test.js
adds a new util to process a queue asynchronously with a defined concurrency level.
i used to copy paste this function many times but finally decided to donate it to shared.
=> feat(utils): add process-queue

renovate.json
=> chore: don't upgrade to unified 10.x as it requires ESM

packages/helix-shared-config/src/schemas/index.schema.json
With Helix 3, it turns out that `fetch` and source are optional, as they can be derived:
- `fetch`: https://{ref}--{repo}--{owner}.hlx3.live/{path}
- `source`: would contain the extension, but in Helix 3, we don't need to add `.html` anymore
=> fix: fetch and source should be optional

packages/helix-shared-bounce/README.md, packages/helix-shared-bounce/src/bounce.js, packages/helix-shared-bounce/test/bounce.test.js
when calling the function directly, for instance in a test, the `context.invocation` property may be unset. This patch guards against this case by initializing it with an empty object.
=> fix(bounce): guard against missing `context.invocation`

.circleci/config.yml, packages/helix-shared-utils/package.json, packages/helix-shared-utils/src/utils.js, packages/helix-shared-utils/test/surrogate.test.js
BREAKING CHANGE: the encoding for surrogate computation changed from the regular to the url-safe base64 encoding. i.e. '+' -> '-', '/' -> '_'.
see https://github.com/adobe/helix-pipeline-service/issues/282
=> feat: use base64url encoding for surrogate computation

packages/helix-shared-body-data/.renovaterc.json, packages/helix-shared-body-data/package-lock.json, packages/helix-shared-body-data/package.json, packages/helix-shared-bounce/.renovaterc.json, packages/helix-shared-bounce/package-lock.json, packages/helix-shared-bounce/package.json, packages/helix-shared-config/.renovaterc.json, packages/helix-shared-config/package-lock.json, packages/helix-shared-config/package.json, packages/helix-shared-ims/.renovaterc.json, packages/helix-shared-ims/package-lock.json, packages/helix-shared-ims/package.json, packages/helix-shared-indexer/.renovaterc.json, packages/helix-shared-indexer/package-lock.json, packages/helix-shared-indexer/package.json
uses the `^` version for helix-fetch and universal, thus allowing upstream projects to better dedupe them. this can prevent errors where `instanceof` checks otherwise fail.
=> fix: don't pin helix-fetch and universal for better deduping

packages/helix-shared-bounce/README.md, packages/helix-shared-bounce/src/bounce.js, packages/helix-shared-bounce/test/bounce.test.js
The plugin options can take a `debounce` function property that is called with the `request` and
`context`. if it returns a non falsy value the wrapped function will not be bounced.
```js
function debounce(req, context) {
if (context.pathInfo.suffix === '/about') {
return true;
}
return false;
}
module.exports.main = wrap(main)
.with(bounce, { responder: fast, debounce });
```
=> feat: add support for debounce function

packages/helix-shared-config/src/fetchconfig/cache.js
Causes a line being logged when starting a debugging session:
```
(node:11906) [LRU_CACHE_OPTION_maxAge] DeprecationWarning: The maxAge option is deprecated. Please use options.ttl instead.
```
see: https://www.npmjs.com/package/lru-cache/v/7.8.2#ttl
=> fix: suppress deprecation warning (maxAge has been replaced by ttl)

package-lock.json, packages/helix-shared-config/src/schemas/mountpoint.schema.json, packages/helix-shared-config/test/mountpoints.test.js, packages/helix-shared-config/test/specs/mountconfigs/complex.json, packages/helix-shared-config/test/specs/mountconfigs/complex.yaml
allow fstab to specify tenant-id:
```yaml
mountpoints:
/:
url: https://sp-global.com
type: onedrive
tenantId: 1234
```
this is required for sharepoint access that doesn't follow the `<tenantid>.sharepoint.com` pattern
=> feat: allow to specify microsoft tenantid for custom domains

package-lock.json, packages/helix-shared-config/src/MountConfig.js, packages/helix-shared-config/test/mountpoints.test.js, packages/helix-shared-config/test/specs/mountconfigs/complex.json, packages/helix-shared-config/test/specs/mountconfigs/complex.yaml
the `fstab.resolve('/foo/')` used to return a mountpoint with `/foo` as `relPath`.
with this change, the trailing slash is preseved, i.e. it will return `/foo/`
since this this is quite different behaviour, as clients might have expected the `relPath` always to end w/o slash, it is a 
🥁🥁🥁🥁
**BREAKING CHANGE**: rel path keeps trailing slash after resolution
=> fix: keep trailing slash in relPath of matched mountpoint

packages/helix-shared-config/src/IndexConfig.js, packages/helix-shared-config/test/indexconfigs.test.js
Allows replacing an index definition (e.g. to add or remove properties)
=> feat: replace index definition

packages/helix-shared-tokencache/src/FSCachePlugin.d.ts, packages/helix-shared-tokencache/src/FSCachePlugin.js, packages/helix-shared-tokencache/src/MemCachePlugin.d.ts, packages/helix-shared-tokencache/src/MemCachePlugin.js, packages/helix-shared-tokencache/src/S3CachePlugin.d.ts, packages/helix-shared-tokencache/src/S3CachePlugin.js, packages/helix-shared-tokencache/src/getCachePlugin.js, packages/helix-shared-tokencache/test/fs-cache-plugin.test.js, packages/helix-shared-tokencache/test/getCachePlugin.test.js, packages/helix-shared-tokencache/test/mem-cache-plugin.test.js
... and add a `location` to the cache plugin
=> feat: move getCachePlugin to shared

packages/helix-shared-indexer/src/index-resource.js, packages/helix-shared-indexer/test/index-resource.test.js
ensure arguments to `match` is an array
=> fix: match should enforce array input

packages/helix-shared-secrets/src/secrets-wrapper.js, packages/helix-shared-secrets/test/secrets-wrapper.test.js
In some scenarios it may make sense to have the secrets path (name) as used by the wrapper be dynamically specified. One example is to dynamically set the secrets path (name) depending on the function version. This for example to distinguish secrets intended for production versus ones for development based on the function version (e.g. `ci` vs `v1`).
=> feat: support resolving secrets name via function
